# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d725234403b04c67a93c8bfb46e5cb77b891f3d3f5f439b63e4dd3029ae532599fcbab86ca6e191909a48ab1618aca0f0ca32b05709ff1e25abb416f448f3ed1

test:
  secret_key_base: 5756d946337902a5ef3444225d5c886d8bfff02daf2e2c9a03e1fe584362a556150a01f1d0f2639c2ab3c1e280c55d7c8076f1a9e6113025c4fdf2ef8e9a1e9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
